#ifndef TRAIN_DEFINES_H
#define TRAIN_DEFINES_H

#define TRAIN_SIZE 81
#define SWITCH_SIZE 257
	#define NORMAL_SWITCH_SIZE_LOW 1
	#define NORMAL_SWITCH_SIZE_HIGH 18
	#define SPECIAL_SWITCH_SIZE_LOW 153
	#define SPECIAL_SWITCH_SIZE_HIGH 156
#define DECODER_SIZE 5
#define SENSOR_SIZE DECODER_SIZE*16

typedef enum TR_Command{
	TR_QUIT = -1,
	TR_TRAIN = 1,
	TR_REVERSE = 2,
	TR_SWITCH = 3,
	TR_SENSOR = 4,
} TR_Command;

typedef enum TR_Direction{
	TR_FORWARD = -1,
	TR_BACKWARD = 1
} TR_Direction;

#endif //TRAIN_DEFINES_H
